encoding: utf-8

baseurl: ""

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

plugins:
  - jekyll-feed

# Socials
github: jhartzer
linkedin: JacobHartzer
semanticscholar: 118011043
orcid: 0000-0002-3051-2213
rss_icon: true

collections:
  meme-of-the-monday:
    output: true
    permalink: /meme-of-the-monday/:name/

defaults:
  - scope:
      path: ""
      type: "meme-of-the-monday"
    values:
      layout: meme-of-the-monday
